// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnlineVoteApplication.Models
{
    public partial class ContestManagement
    {
        public int Id { get; set; }
        public string ContestentName { get; set; }
        public int Age { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public string PartyName { get; set; }
        public string Symbol { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string ContestentImage { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
    }
}