// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnlineVoteApplication.Models
{
    public partial class ElectionPooling
    {
        public int Id { get; set; }
        public string ContestentId { get; set; }
        public string PartyId { get; set; }
        public string VoterId { get; set; }
        public DateTime? CreatedDate { get; set; }
    }
}